# Stage 1: Build the Nuxt.js application
FROM node:16-alpine as build

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN {{packageManager}} install

# Copy the rest of the application code
COPY . .

# Build the Nuxt.js application
RUN {{packageManager}} run build

# Stage 2: Serve the application using a lightweight server
FROM node:16-alpine as production

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install only production dependencies
RUN {{packageManager}} install --production

# Copy the built application from the build stage
COPY --from=build /app/.nuxt ./.nuxt
COPY --from=build /app/static ./static
COPY --from=build /app/nuxt.config.js ./

# Expose the application port (default is 3000 for Nuxt.js)
EXPOSE 3000
ARG PACKAGE_MANAGER={{packageManager}}
CMD ["${PACKAGE_MANAGER}", "start"]

