# Use the official Nginx image as the base image
FROM nginx:alpine

# Set the working directory inside the container
WORKDIR /usr/share/nginx/html

# Copy your HTML files and other assets into the Nginx HTML folder
COPY . .

# Expose port 80 to the host
EXPOSE 80

# Command to start Nginx
CMD ["nginx", "-g", "daemon off;"]
