# Dockerfile for Laravel project
FROM php:7.4-fpm
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd
WORKDIR /var/www
COPY . .
RUN composer install
EXPOSE 8000
CMD php artisan serve --host=0.0.0.0 --port=8000