# Stage 1: Build the Nuxt.js application
FROM node:18-alpine AS build

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the Nuxt.js application
RUN npm run build

# Stage 2: Serve the application using Nginx
FROM nginx:alpine AS production

# Copy the built application from the build stage
COPY --from=build /app/.output/public /usr/share/nginx/html


# Expose the application port (default is 80 for Nginx)
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]